#'@title GWRFC outputs report
#'@description This function uses outputs from GWRFC and generate a report of dependent variable, using its classes to generate a statistical summary and plots.
#'@param dependent_varName string. Dependent variable name. Only required for edit titles of plots. Recommended full names not longer than 8 words.
#'@param GWRFC_folder string. A folder where GWRFC outputs are stored. The function do not works if it finds more than an output.
#'@param plots logical. If true, plots are returned.
#'@param size_plots numeric. Base dimensions for plots. Set X and Y as centimeters: c(22,22)
#'@param output_folder string. Output folder where outputs will be stored.
#'@return The results of the function includes: \enumerate{
#'                            \item A report summarizing GWRFC outputs (stored in a .rds file)
#'                            \item Plots derived from report summaries.
#'                           }
#'@examples
#'#based in the example showed with the execution of GWRFC
#'list.files("C:/DATA/demo/deforestation",full.names=T,pattern=".shp") #get the output filename from GWRFC function
#'
#'GWRFC_repo(dependent_varName = "FAO deforestation rate (2001-2010)",
#'          GWRFC_folder = "E:/demo/test",
#'          plots = T,
#'          output_folder = "E:/demo/test/repo") #check this folder for outputs generated by the function.
#'@export

GWRFC_repo <- function(
  dependent_varName,
  GWRFC_folder,
  plots=T,
  size_plots=c(22,22),
  output_folder
){

  ##### PREPARE DATA #####

  print("Reading data...")

  #random + test
  set.seed(666)
  #output folder
  dir.create(output_folder,showWarnings = F, recursive = T)
  #read GWRFC
  gwrfc.shp <- list.files(GWRFC_folder,full.names=T,pattern=".shp$")
  if(length(gwrfc.shp)>=5){
    stop("More than one output from GWRFC are found. Program exit.")
  }
  gwrfc.shp <- lapply(gwrfc.shp,function(x){
    x.shp <- shapefile(x)
    x.nam <- gsub(".shp","",tail(unlist(strsplit(basename(x),"_")),1))
    return(list(x.shp,x.nam))
  })
  names(gwrfc.shp) <- sapply(gwrfc.shp,"[[",2)
  gwrfc.shp <- sapply(gwrfc.shp,"[[",1)

  #### FUNCTIONS ####

  Mode <- function(x) {
    ux <- unique(x)
    ux[which.max(tabulate(match(x, ux)))]
  }

  x.summary <- function(x,fun){
    #x <- x[complete.cases(x),]
    if(fun=="Mode"){
      x.agr <- stats::aggregate(x[,1:(ncol(x)-1),drop=F],
                                by = list(x$DEP),
                                FUN = Mode)
    }else{
      x.agr <- stats::aggregate(x[,1:(ncol(x)-1),drop=F],
                                by = list(x$DEP),
                                FUN = fun)
    }
    names(x.agr)[1] <- "DEP"
    x.agr <- reshape::melt(x.agr,id.vars="DEP")
    names(x.agr)[3] <- fun
    return(x.agr)
  }

  report.quanti <- function(x,y){
    x.clus <- x[,y]
    x <- x[,1:(ncol(x)-1),drop=F]
    x <- x[,sapply(x,is.numeric),drop=F]
    valid.cols <- sapply(x,function(x.col){
      x.col <- all(is.na(x.col))
    })
    x <- x[,!valid.cols,drop=F]
    if(length(x)!=0){
      x$DEP <- x.clus
      x.report <- x.summary(x,"mean")
      names(x.report)[3] <- "mean"
      x.report$sd <- x.summary(x,"sd")[,3]
      x.report$min <- x.summary(x,"min")[,3]
      x.report$max <- x.summary(x,"max")[,3]
      x.act <- T
    }else{
      x.report <- NA
      x.act <- F
    }
    return(list(x.report,x.act))
  }

  report.quali <- function(x,y){
    x.clus <- x[,y]
    x <- x[,1:(ncol(x)-1)]
    x <- x[,!sapply(x,is.numeric),drop=F]
    if(length(x)!=0){
      x$DEP <- x.clus
      x.report <- x.summary(x,"Mode")
      x.act <- T
    }else{
      x.report <- NA
      x.act <- F
    }
    return(list(x.report,x.act))
  }

  ACC.fun <- function(){
    #initial vars
    acc.plot <- list()
    acc.sum <- list()
    #probabilities
    acc.prob <- gwrfc.shp$ACC@data
    acc.prob <- acc.prob[,grep("^P_",names(acc.prob))]
    acc.prob$DEP <- gwrfc.shp$ACC@data$DEP
    acc.prob <- report.quanti(acc.prob,ncol(acc.prob))[[1]]
    acc.sum$PROB <- acc.prob
    acc.plot$PROB <- ggplot(acc.sum$PROB,aes(x=DEP,y=as.character(variable),fill=mean)) +
      theme(axis.text.x=element_text(hjust = 1,angle=45)) +
      geom_tile() +
      labs(title=dependent_varName,
           subtitle = paste0("Predicted probabilities for observed classes"),
           x="CLASSES",y="PROBABILITIES")
    #kappa
    acc.kap <- gwrfc.shp$ACC@data
    acc.kap <- acc.kap[,ncol(acc.kap),drop=F]
    acc.kap$DEP <- gwrfc.shp$ACC@data$DEP
    acc.sum$KAPPA <- report.quanti(acc.kap,2)[[1]]
    acc.plot$KAPPA <- ggplot(acc.kap,aes(x=DEP,y=KAPPA,fill=DEP,group=DEP)) +
      theme(axis.text.x=element_text(hjust = 1,angle=45)) +
      geom_boxplot() +
      labs(title="",
           subtitle = paste0("Kappa index from out-of-bag random forest models"),
           x="CLASSES",y="KAPPA")
    #fail?
    acc.fai <- gwrfc.shp$ACC@data$FAIL
    acc.fai <- table(acc.fai)
    if(length(acc.fai)==1 & names(acc.fai)[1] == "no"){
      acc.fai <- as.numeric(acc.fai)
      acc.fai <- data.frame(fail=c("yes","no"),count=c(0,acc.fai))
    }else if(length(acc.fai)==1 & names(acc.fai)[1] == "yes"){
      acc.fai <- as.numeric(acc.fai)
      acc.fai <- data.frame(fail=c("yes","no"),count=c(acc.fai,0))
    }else{
      acc.fai <- as.numeric(acc.fai)
      acc.fai <- data.frame(fail=c("yes","no"),count=c(acc.fai[2],acc.fai[1]))
    }
    acc.fai$perc <- c((acc.fai$count[1]*100) / sum(acc.fai$count),(acc.fai$count[2]*100) / sum(acc.fai$count))
    acc.sum$FAIL <- acc.fai
    acc.plot$FAIL <- ggplot(acc.fai,aes(x=fail,y=perc,fill=fail)) +
      geom_bar(stat="identity") +
      geom_text(aes(label=paste0(round(perc,1),"%"), vjust=0)) +
      labs(title="",
           subtitle = paste0("Predicted vs observed missmatch (percentage)"),
           x="FAIL ?",y="COUNT")
    #predicted vs observed
    acc.pred <- data.frame(table(gwrfc.shp$ACC@data$PRED))
    names(acc.pred) <- c("classes","PRED")
    acc.pred$DEP <- data.frame(table(gwrfc.shp$ACC@data$DEP))$Freq
    acc.pred$diff <- acc.pred$PRED - acc.pred$DEP
    acc.sum$COMP <- acc.pred
    acc.plot$COMP <- ggplot(acc.pred,aes(x=classes,y=diff,fill=classes)) +
      theme(axis.text.x=element_text(hjust = 1,angle=45)) +
      geom_bar(stat="identity") +
      geom_hline(yintercept=0,linetype="dotted",color="black",size=0.75) +
      labs(title="",
           subtitle = paste0("Prediction vs observed missmatch (count per class)"),
           x="CLASS",y="COUNT")
    return(list(acc.plot,acc.sum))
  }

  LVI.fun <- function(){
    #initial vars
    lvi.plot <- list()
    lvi.sum <- list()
    #lvi
    lvi.val <- gwrfc.shp$LVI@data
    lvi.val$DEP <- gwrfc.shp$ACC@data$DEP
    lvi.val <- lvi.val[2:ncol(lvi.val)]
    lvi.val <- report.quanti(lvi.val,ncol(lvi.val))[[1]]
    lvi.sum$LVI <- lvi.val
    lvi.plot$LVI <- ggplot(lvi.val, aes(x = sort(variable), y = mean, col = DEP, group = DEP)) +
      geom_polygon(fill = NA) + coord_polar() +
      geom_hline(yintercept=0,linetype="dotted",color="black",size=0.75) +
      labs(title=dependent_varName,
           subtitle = paste0("Local variables importance (LVI), extracted as means"),
           x="VARIABLES",y="LVI (score)")
    return(list(lvi.plot,lvi.sum))
  }

  PDP.fun <- function(){
    #initial vars
    pdp.plot <- list()
    pdp.sum <- list()
    #YHAT
    yhat.val <- gwrfc.shp$YHAT@data
    yhat.val$DEP <- gwrfc.shp$ACC@data$DEP
    yhat.val <- yhat.val[2:ncol(yhat.val)]
    pdp.sum$YHAT <- report.quanti(yhat.val,ncol(yhat.val))[[1]]
    #pdp numeric
    pdp.num <- gwrfc.shp$PDP@data
    pdp.num <- pdp.num[,sapply(pdp.num,is.numeric)]
    num.nam <- names(pdp.num)
    pdp.num$DEP <- gwrfc.shp$ACC@data$DEP
    pdp.sum$NUM <- report.quanti(pdp.num,ncol(pdp.num))[[1]]
    valid.cols <- sapply(pdp.num,function(x.col){
      x.col <- all(is.na(x.col))
    })
    pdp.num <- pdp.num[,!valid.cols,drop=F]
    #pdp.num <- pdp.num[complete.cases(pdp.num),]
    scale.vals <- scale(pdp.num[,1:(ncol(pdp.num)-1)])
    pdp.num[,1:(ncol(pdp.num)-1)] <- scale.vals
    scale.vals <- paste0(names(pdp.num)[1:(ncol(pdp.num)-1)],"\n","(",
                         round(attr(scale.vals,"scaled:center"),2)," ? ",
                         round(attr(scale.vals,"scaled:scale"),2),")")
    names(pdp.num)[1:(ncol(pdp.num)-1)] <- scale.vals
    ind.val <- split(1:(ncol(pdp.num)-1), ceiling(seq_along(1:(ncol(pdp.num)-1))/10))
    #define php.YHAT
    pdp.yhat <- yhat.val[,num.nam]
    valid.cols <- sapply(pdp.yhat,function(x.col){
      x.col <- all(is.na(x.col))
    })
    pdp.yhat <- pdp.yhat[,!valid.cols,drop=F]
    pdp.yhat$DEP <- gwrfc.shp$ACC@data$DEP
    #pdp.yhat <- pdp.yhat[complete.cases(pdp.yhat),]
    names(pdp.yhat) <- c(scale.vals,"DEP")
    #plot pdp numeric vs YHAT
    pdp.plot$NUM <- lapply(ind.val,function(x){
      x.yhat <- pdp.yhat[,c(x,ncol(pdp.yhat))]
      x.yhat <- report.quanti(x.yhat,ncol(x.yhat))[[1]]
      x.df <- reshape::melt(pdp.num[,c(x,ncol(pdp.num))],id.vars="DEP")
      x.plot <- ggplot(x.df,aes(x=sort(variable), y=value,fill=DEP,group=variable)) +
        theme(axis.text.x=element_text(hjust = 1,angle=45)) +
        geom_boxplot(position=position_dodge(width = 0.75),outlier.alpha=0.33,show.legend = T) +
        geom_hline(yintercept=0,linetype="dotted",color="black",size=0.75) +
        coord_cartesian(ylim=c(-2,2)) +
        labs(title=dependent_varName,
             subtitle=paste0("Partial dependence plot (PDP): quantitative variables values (standarized) that maximized YHAT prediction, set ",x[1]," - ",tail(x,1)),
             x="VARIABLES (mean,sd)",
             y="Z-SCORES") +
        geom_line(aes(x=sort(variable),y=mean,group=1),x.yhat,size=1.5,color="black",linetype="dashed") +
        geom_point(aes(x=sort(variable),y=mean,group=1),x.yhat,size=4,color="black",fill="white",shape=21) +
        scale_y_continuous(sec.axis = dup_axis(~./5,name="YHAT (mean)")) +
        facet_wrap(.~DEP)
      return(x.plot)
    })
    #pdp categorical
    pdp.cat <- gwrfc.shp$PDP@data
    pdp.cat <- pdp.cat[,!sapply(pdp.cat,is.numeric)]
    pdp.cat$DEP <- gwrfc.shp$ACC@data$DEP
    pdp.cat <- pdp.cat[,2:ncol(pdp.cat)]
    valid.cols <- sapply(pdp.cat,function(x.col){
      x.col <- all(is.na(x.col))
    })
    pdp.cat <- pdp.cat[,!valid.cols,drop=F]
    #pdp.cat <- pdp.cat[complete.cases(pdp.cat),]
    pdp.sum$CAT <- report.quali(pdp.cat,ncol(pdp.cat))[[1]]
    ind.val <- split(1:(ncol(pdp.cat)-1), ceiling(seq_along(1:(ncol(pdp.cat)-1))/5))
    #restore php.YHAT
    pdp.yhat <- gwrfc.shp$PDP@data
    pdp.yhat <- pdp.yhat[,!sapply(pdp.yhat,is.numeric)]
    pdp.yhat <- pdp.yhat[,2:ncol(pdp.yhat)]
    pdp.yhat.ls <- list()
    for(j in 1:ncol(pdp.yhat)){
      yhat.var <- data.frame(yhat=yhat.val[,names(yhat.val) %in% names(pdp.yhat)[j]],class=pdp.yhat[,j])
      yhat.var <- yhat.var[complete.cases(yhat.var),]
      yhat.var <- stats::aggregate(yhat.var$yhat,by = list(yhat.var$class),FUN = "mean")
      yhat.var$variable <- names(pdp.yhat)[j]
      names(yhat.var) <- c("CLASS","YHAT","variable")
      pdp.yhat.ls[[j]] <- yhat.var
    }
    pdp.yhat <- do.call("rbind.data.frame",pdp.yhat.ls)
    #plot pdp vs yhat
    pdp.plot$CAT <- lapply(ind.val,function(x){
      x.df <- reshape::melt(pdp.cat[,c(x,ncol(pdp.cat))],id.vars = "DEP")
      x.yhat <- levels(x.df$variable)
      x.yhat <- pdp.yhat[pdp.yhat$variable %in% x.yhat,]
      x.plot <- ggplot(x.df,aes(x=value,fill=DEP)) +
        theme(axis.text.x=element_text(hjust = 1,angle=45)) +
        geom_bar(position = "dodge") +
        coord_flip() +
        labs(title=dependent_varName,
             subtitle=paste0("Partial dependence plot (PDP): qualitative variables classes count when YHAT prediction is maximum, set ",x[1]," - ",tail(x,1)),
             y="COUNT",x="CLASSES") +
        facet_wrap(~variable,scales="free",ncol=5)
      return(x.plot)
    })
    return(list(pdp.plot,pdp.sum))
  }

  #### CREATE REPORT ####

  print("Start report")

  rep.sum <- list()
  for(i in 1:length(gwrfc.shp)){
    #ACCURACY
    if(names(gwrfc.shp)[i]=="ACC"){
      rep.sum$ACC <- ACC.fun()[[2]]
      #arrange plots
      acc.plot <- ACC.fun()[[1]]
      acc.plot <- gridExtra::grid.arrange(acc.plot$PROB,acc.plot$KAPPA,
                                          acc.plot$FAIL,acc.plot$COMP,
                                          ncol=2,nrow=2,
                                          layout_matrix=rbind(c(1,2),c(3,4)))
      output.name <- paste0(output_folder,"/ACC_sum.jpg")
      ggsave(acc.plot,filename=output.name,dpi = 300, width=(size_plots[1]/1.25)+4,height=size_plots[2]/1.25,units="cm")
    }
    #LVI
    if(names(gwrfc.shp)[i]=="LVI"){
      rep.sum$LVI <- LVI.fun()[[2]]
      lvi.plot <- LVI.fun()[[1]]
      output.name <- paste0(output_folder,"/LVI_rad.jpg")
      ggsave(lvi.plot$LVI,filename=output.name,dpi = 300, width=size_plots[1]/1.5,height=size_plots[2]/1.5,units="cm")
    }
    #PDP
    if(names(gwrfc.shp)[i]=="PDP" & names(gwrfc.shp)[i+1]=="YHAT"){
      rep.sum$PDP <- PDP.fun()[[2]]
      pdp.plot <- PDP.fun()[[1]]
      for(j in 1:length(pdp.plot$NUM)){
        plot.j <- pdp.plot$NUM[[j]]
        output.name <- paste0(output_folder,"/PDP_num_",j,".jpg")
        ggsave(plot.j,filename=output.name,dpi = 300, width=size_plots[1],height=(size_plots[2]/3)*2,units="cm")
      }
      for(j in 1:length(pdp.plot$CAT)){
        plot.j <- pdp.plot$CAT[[j]]
        output.name <- paste0(output_folder,"/PDP_cat_",j,".jpg")
        ggsave(plot.j,filename=output.name,dpi = 300, width=size_plots[1],height=(size_plots[2]/3)*2,units="cm")
      }
    }
  }

  #### SAVE REPORT ####

  print("Saving report...")

  #save reports

  output.name <- paste0(output_folder,"/GWRFC_repo.rds")
  saveRDS(rep.sum,output.name)
  print("****CLUSrepo end sucessfully*****")
  return(rep.sum)
}




